var ABSENCE_RULE = "Absence Rule";
var ABSENCE_SCHEDULE = "Abssence Schedule";
var ABSENCE_STATUS = "Absence Status";
var ABSENCE_TRANSACTION = "Absence Transaction";
var ACCOUNT = "Account";
var ACCOUNT_PAYABLE_REPORT = "Account Payable Report";
var ACCOUNT_PERIOD = "Account Period";
var ACCOUNT_RECEIVABLE_REPORT = "Account Receivable Report";
var ACCOUNT_TYPE = "Account Type";
var ACCOUNTING = "Accounting";
var ACCOUNTING_REPORT = "Accounting Report";
var ACTIVITY = "Activity";
var ADDRESS_ACCOUNTING = "Address Accounting";
var ADDRESS_BOOK = "Address Book";
var ADDRESS_TYPE = "Address Type";
var ADMIN = "Admin";
var ADMIN_PANEL = "Admin Panel";
var APPLICANT = "Applicant";
var APPLICATION = "Application";
var ARTICLE = "Article";
var ARTICLE_GROUP = "Article Group";
var ARTICLE_PURCHASING_REPORT = "Article Purchasing Report";
var ARTICLE_STATUS = "Article Status";
var ARTICLE_TYPE = "Article Type";
var AVERAGE_PRICE = "Average Price";
var BACK = "Back";
var BACK_TO_HOME = "Back to Home";
var BALANCE_SHEET = "Balance Sheet";
var BANK = "Bank";
var BILL_OF_MATERIAL = "Bill of Material";
var BLOG = "Blog";
var BROWSER = "Browser";
var BUDGET = "Budget";
var BUSINESS_GROUP = "Business Group";
var CASH_BANK = "Cash / Bank";
var CATEGORY = "Category";
var CITY = "City";
var COLOUR = "Colour";
var COMMON = "Common";
var COMPANY = "Company";
var COMPANY_TYPE = "Company Type";
var COMPONENT = "Component";
var COMPONENT_CATEGORY = "Component Category";
var CONTACT_TYPE = "Contact Type";
var COUNTRY = "Country";
var COST_OF_GOODS_SOLD = "Cost of Goods Sold";
var COST_OF_SALES = "Cost of Sales";
var CREDIT_NOTE = "Credit Note";
var CREDIT_NOTE_LIST = "Credit Note List";
var CURRENCY = "Currency";
var CUSTOMER = "Customer";
var CUSTOMER_GROUP = "Customer Group";
var CUSTOMER_INVOICE = "Customer Invoice";
var CUSTOMER_INVOICE_LIST = "Customer Invoice List";
var DASHBOARD = "Dashboard";
var DATABASE = "Database";
var DEBIT_NOTE = "Debit Note";
var DEBIT_NOTE_LIST = "Debit Note List";
var DEPARTMENT = "Department";
var DEPARTMENT_ACCOUNTING = "Department Accounting";
var DIRECT_FACTORY_WAGE_STANDARDS = "Direct/Factory Wage Standards";
var EDUCATION = "Education";
var EDUCATION_MAJOR = "Education Major";
var EMAIL = "Email";
var EMPLOYEE = "Employee";
var EMPLOYEE_BENEFIT = "Employee Benefit";
var EMPLOYEE_ONLEAVE = "Employee Onleave";
var EMPLOYEE_SCHEDULE = "Employee Schedule";
var EMPLOYEE_STATUS = "Employee Status";
var EMPLOYEE_TAX = "Employee Tax";
var EMPLOYEE_TYPE = "Employee Type";
var EMPLOYEE_WAGE = "Employee Wage";
var ENTER_USER = "Enter username";
var EXPENSE_CASH_BANK = "Expense Cash Bank";
var EXPENSE_CASH_BANK_LIST = "Expense Cash Bank List";
var FAMILY_RELATION = "Family Relation";
var FACTORY_WAGE_STANDARDS = "Factory Wage Standards";
var FILE_MANAGER = "File Manager";
var FINISH_GOODS_TRANSFER = "Finish Goods Transfer";
var FINISH_GOODS_TRANSFER_LIST = "Finish Goods Transfer List";
var FIX_ASSET = "Fix Asset";
var FISCAL_PROFIT_LOSS = "Fiscal Profit Loss";
var FORM_REQUEST = "Form Request";
var FORM_REQUEST_LIST = "Form Request List";
var FORM_REQUEST_PLAN = "Form Request Plan";
var FORM_REQUEST_PLAN_LIST = "Form Request Plan List";
var GENERAL_CASH_BANK = "General Cash/Bank";
var GENERAL_CASH_BANK_LIST = "General Cash/Bank List";
var GENERAL_COSTS = "General Costs";
var GENERAL_INCOME_INVOICE = "General Income Invoice";
var GENERAL_INCOME_INVOICE_LIST = "General Income Invoice List";
var GENERAL_JOURNAL = "General Journal";
var GENERAL_LEDGER = "General Ledger";
var GENERAL_LEDGER_REPORT = "General Ledger Report";
var GENERAL_SUPPLIER_INVOICE = "General Supplier Invoice";
var GENERAL_SUPPLIER_INVOICE_LIST = "General Supplier Invoice List";
var GOODS_ISSUE = "Goods Issue";
var GOODS_ISSUE_LIST = "Goods Issue List";
var GOODS_ISSUE_RETURN = "Goods Issue Return";
var GOODS_ISSUE_RETURN_LIST = "Goods Issue Return List";
var GOODS_RECEIVE = "Goods Receive";
var GOODS_RECEIVE_LIST = "Goods Receive List";
var GOODS_RETURN = "Goods Return";
var GOODS_RETURN_LIST = "Goods Return List";
var GOODS_STOCK = "Goods Stock";
var GROUP_ACCESS = "Group Access";
var HOLIDAY = "Holiday";
var HOME = "Home";
var HOSPITAL = "Hospital / Clinic";
var IDENTITY_TYPE = "Identity Type";
var INCOME_CASH_BANK = "Income Cash Bank";
var INCOME_CASH_BANK_LIST = "Income Cash Bank List";
var INVENTORY_REPORT = "Inventory Report";
var INVALID_CREDENTIAL = "Invalid credentials";
var INVALID_DATA_RETRIEVED = "Invalid Data Retrieved";
var INVALID_EMAIL = "Invalid email format";
var INVALID_PASSWORD = "Invalid password";
var INVALID_USER = "Invalid user";
var JOBS = "Jobs";
var LANGUAGE = "Language";
var LANGUAGE_VALUE = "Language Value";
var LOADING = "Loading ...";
var LOGIN = "Login";
var LOGIN_TO_ACCOUNT = "Login to your account";
var LOGGING_IN = "Logging in...";
var LOGOUT = "Logout";
var MARITAL_STATUS = "Marital Status";
var MEAL_ABSENCE = "Meal Absence";
var MENU_ACCESS = "Menu Access";
var METODE_PEMBAYARAN = "Metode Pembayaran";
var MODULE = "Module";
var NAME = "Name";
var NEWS = "News";
var NO_ACCOUNT = "Don't have an account?";
var OBJECT_MENU = "Object Menu";
var OCCUPATION = "Occupation";
var ONLEAVE_TRANSACTION = "Onleave Transaction";
var ONLEAVE_TYPE = "Onleave Type";
var ORDERS = "Orders";
var ORGANIZATION = "Organization";
var ORGANIZATION_LEVEL = "Organization Level";
var ORGANIZATION_MANAGEMENT_LIST = "Organization Management List";
var ORGANIZATION_STRUCTURE = "Organization Structure";
var OWNERSHIP = "Ownership";
var PARAMETER = "Parameter";
var PASSWORD = "Password";
var PASSWORD_MIN_6 = "Password must be at least 6 characters";
var PAYROLL_PERIODE = "Payroll Periode";
var PAYROLL_PROCESS = "Payroll Process";
var PAYROLL_REPORT = "Payroll Report";
var PERMIT_EXIT_TRANSACTION = "Permit Exit Transaction";
var PERMIT_EXIT_TYPE = "Permit Exit Type";
var PERMIT_IN_TRANSACTION = "Permit In Transaction";
var PERMIT_IN_TYPE = "Permin In Type";
var PERSONALIZATION = "Personalization";
var PERSONNEL = "Personnel";
var PERSONNEL_REPORT = "Personnel Report";
var POS = "POS";
var POSITION = "Position";
var PRICE_CATEGORY = "Price Category";
var PRODUCTION = "Production";
var PRODUCTION_OUTPUT = "Production Output";
var PRODUCTION_OUTPUT_LIST = "Production Output List";
var PRODUCTION_PLANNING = "Production Planning";
var PRODUCTION_PLANNING_MASTER = "Production Planning Master";
var PRODUCTION_PLANNING_REPORT = "Production Planning Report";
var PRODUCTION_PROCESS = "Production Process";
var PRODUCTION_REPORT = "Production Report";
var PROFIT_LOSS = "Profit / Loss";
var PROVINCE = "Province";
var PURCHASE_EXPEDITION = "Purchase Expedition";
var PURCHASE_EXPEDITION_LIST = "Purchase Expedition List";
var PURCHASE_ORDER = "Purchase Order";
var PURCHASE_ORDER_LIST = "Purchase Order List";
var PURCHASE_REQUEST = "Purchase Request";
var PURCHASE_REQUEST_LIST = "Purchase Request List";
var PURCHASING = "Purchasing";
var PURCHASING_INFO_RECORD = "Purchasing Info Record";
var QC = "QC";
var QUALIFICATION_PARAMETER = "Qualification Parameter";
var QUALIFICATION_TEST = "Qualification Test";
var RATE = "Rate";
var READ_MORE = "Read More ...";
var RECRUIT_REQUEST_LIST = "Recruit Request List";
var RECURRING_TYPE = "Reccuring Type";
var REF_Q = "RFQ";
var RELIGION = "Religion";
var REMINDER = "Reminder";
var REQUESTED_BY = "Requested By";
var RECRUIT_REQ_TRANSACTION = "Recruit Request Transaction";
var RFQ = "Request For Quotation";
var ROMAWI = "Romawi";
var SALES = "Sales";
var SALES_AREA = "Sales Area";
var SALES_EXPEDITION = "Sales Expedition";
var SALES_EXPEDITION_LIST = "Sales Expedition List";
var SALES_FORECAST = "Sales Forecast";
var SALES_FORECAST_LIST = "Sales Forecast List";
var SALES_LIST = "Sales List";
var SALES_ORDER = "Sales Order";
var SALES_ORDER_LIST = "Sales Order List";
var SERVER_INFORMATION = "Server Information";
var SERVICE = "Service";
var SERVICE_LIST = "Service List";
var SEX = "Sex";
var SICKNESS_TRANSACTION = "Sickness Transaction";
var SIGN_IN = "Sign In";
var SIGN_UP = "Sign Up";
var SLIDE_SHOW = "Slide Show";
var SPECIFIC_NUMBER_RANGE_OBJECT = "Specific Number Range Object";
var STATUS = "Status";
var STOCK_ADJUSMENT = "Stock Adjusment";
var STOCK_ADJUSTMENT_REPORT = "Stock Adjustment Report";
var SUPPLIER = "Supplier";
var SUPPLIER_INVOICE = "Supplier Invoice";
var SUPPLIER_INVOICE_LIST = "Supplier Invoice List";
var TAX = "Tax";
var TAX_ACCOUNTING = "Tax Accounting";
var TAX_WAGE_PROGRESSIF = "Tax Wage Progressif";
var TERMINATE_REQUEST = "Terminate Request Transaction";
var TERMINATE_REQUEST_LIST = "Terminate Request List";
var THEME = "Theme";
var TIME_MANAGEMENT_REPORT = "Time Management Report";
var TITLE = "Title";
var TRANSFER_STOCK_IN = "Transfer Stock In";
var TRANSFER_STOCK_LIST = "Transfer Stock List";
var TRANSFER_STOCK_OUT = "Transfer Stock Out";
var TRANSACTION_LOG = "Transaction Log";
var TYPE_OF_SERVICE = "Type of Service";
var UNIT_OF_MEASURE = "Unit of Measure";
var USER = "User";
var USER_ACCESS = "User Access";
var USERS = "Users";
var VENDOR_DOCUMENT = "Vendor Document";
var VENDOR_PO = "Vendor PO";
var WAGE_AND_TAX = "Wage and Tax";
var WAGE_TYPE = "Wage Type";
var WAREHOUSE = "Warehouse";
var WARNING_LETTERS = "Warning Letters";
var WARNING_LETTERS_TYPE = "Warning Letters Type";
var WELCOME = "WELCOME";
var WELCOME_BACK = "Welcome Back";
var WIDGET = "Widget";
var WORK_TIME = "Work Time";
var WORKFLOW = "Workflow";
var YOU_ARE_NOT_AUTHORIZED = "You are not authorized";
var YOUR_PROFILE = "Profile";
var INVALID_ENTRY_EMPTY = "{entry} is required";
var INVALID_ENTRY_MIN = "{entry} is min {value}";
var INVALID_ENTRY_MIN_CHAR = "{entry} is min {value} character";
var INVALID_ENTRY_MAX = "{entry} is max {value}";
var INVALID_ENTRY_MAX_CHAR = "{entry} is max {value} character";
var INVALID_ENTRY_NUMBER = "{entry} only number accepted";
var INVALID_ENTRY_EMAIL = "{entry} only email accepted";
var INVALID_ENTRY_FORMAT = "{entry} not match with current format";
var INVALID_ENTRY_MATCH = "{entry} not match with {field}";
const id = {
	ABSENCE_RULE: ABSENCE_RULE,
	ABSENCE_SCHEDULE: ABSENCE_SCHEDULE,
	ABSENCE_STATUS: ABSENCE_STATUS,
	ABSENCE_TRANSACTION: ABSENCE_TRANSACTION,
	ACCOUNT: ACCOUNT,
	ACCOUNT_PAYABLE_REPORT: ACCOUNT_PAYABLE_REPORT,
	ACCOUNT_PERIOD: ACCOUNT_PERIOD,
	ACCOUNT_RECEIVABLE_REPORT: ACCOUNT_RECEIVABLE_REPORT,
	ACCOUNT_TYPE: ACCOUNT_TYPE,
	ACCOUNTING: ACCOUNTING,
	ACCOUNTING_REPORT: ACCOUNTING_REPORT,
	ACTIVITY: ACTIVITY,
	ADDRESS_ACCOUNTING: ADDRESS_ACCOUNTING,
	ADDRESS_BOOK: ADDRESS_BOOK,
	ADDRESS_TYPE: ADDRESS_TYPE,
	ADMIN: ADMIN,
	ADMIN_PANEL: ADMIN_PANEL,
	APPLICANT: APPLICANT,
	APPLICATION: APPLICATION,
	ARTICLE: ARTICLE,
	ARTICLE_GROUP: ARTICLE_GROUP,
	ARTICLE_PURCHASING_REPORT: ARTICLE_PURCHASING_REPORT,
	ARTICLE_STATUS: ARTICLE_STATUS,
	ARTICLE_TYPE: ARTICLE_TYPE,
	AVERAGE_PRICE: AVERAGE_PRICE,
	BACK: BACK,
	BACK_TO_HOME: BACK_TO_HOME,
	BALANCE_SHEET: BALANCE_SHEET,
	BANK: BANK,
	BILL_OF_MATERIAL: BILL_OF_MATERIAL,
	BLOG: BLOG,
	BROWSER: BROWSER,
	BUDGET: BUDGET,
	BUSINESS_GROUP: BUSINESS_GROUP,
	CASH_BANK: CASH_BANK,
	CATEGORY: CATEGORY,
	CITY: CITY,
	COLOUR: COLOUR,
	COMMON: COMMON,
	COMPANY: COMPANY,
	COMPANY_TYPE: COMPANY_TYPE,
	COMPONENT: COMPONENT,
	COMPONENT_CATEGORY: COMPONENT_CATEGORY,
	CONTACT_TYPE: CONTACT_TYPE,
	COUNTRY: COUNTRY,
	COST_OF_GOODS_SOLD: COST_OF_GOODS_SOLD,
	COST_OF_SALES: COST_OF_SALES,
	CREDIT_NOTE: CREDIT_NOTE,
	CREDIT_NOTE_LIST: CREDIT_NOTE_LIST,
	CURRENCY: CURRENCY,
	CUSTOMER: CUSTOMER,
	CUSTOMER_GROUP: CUSTOMER_GROUP,
	CUSTOMER_INVOICE: CUSTOMER_INVOICE,
	CUSTOMER_INVOICE_LIST: CUSTOMER_INVOICE_LIST,
	DASHBOARD: DASHBOARD,
	DATABASE: DATABASE,
	DEBIT_NOTE: DEBIT_NOTE,
	DEBIT_NOTE_LIST: DEBIT_NOTE_LIST,
	DEPARTMENT: DEPARTMENT,
	DEPARTMENT_ACCOUNTING: DEPARTMENT_ACCOUNTING,
	DIRECT_FACTORY_WAGE_STANDARDS: DIRECT_FACTORY_WAGE_STANDARDS,
	EDUCATION: EDUCATION,
	EDUCATION_MAJOR: EDUCATION_MAJOR,
	EMAIL: EMAIL,
	EMPLOYEE: EMPLOYEE,
	EMPLOYEE_BENEFIT: EMPLOYEE_BENEFIT,
	EMPLOYEE_ONLEAVE: EMPLOYEE_ONLEAVE,
	EMPLOYEE_SCHEDULE: EMPLOYEE_SCHEDULE,
	EMPLOYEE_STATUS: EMPLOYEE_STATUS,
	EMPLOYEE_TAX: EMPLOYEE_TAX,
	EMPLOYEE_TYPE: EMPLOYEE_TYPE,
	EMPLOYEE_WAGE: EMPLOYEE_WAGE,
	ENTER_USER: ENTER_USER,
	EXPENSE_CASH_BANK: EXPENSE_CASH_BANK,
	EXPENSE_CASH_BANK_LIST: EXPENSE_CASH_BANK_LIST,
	FAMILY_RELATION: FAMILY_RELATION,
	FACTORY_WAGE_STANDARDS: FACTORY_WAGE_STANDARDS,
	FILE_MANAGER: FILE_MANAGER,
	FINISH_GOODS_TRANSFER: FINISH_GOODS_TRANSFER,
	FINISH_GOODS_TRANSFER_LIST: FINISH_GOODS_TRANSFER_LIST,
	FIX_ASSET: FIX_ASSET,
	FISCAL_PROFIT_LOSS: FISCAL_PROFIT_LOSS,
	FORM_REQUEST: FORM_REQUEST,
	FORM_REQUEST_LIST: FORM_REQUEST_LIST,
	FORM_REQUEST_PLAN: FORM_REQUEST_PLAN,
	FORM_REQUEST_PLAN_LIST: FORM_REQUEST_PLAN_LIST,
	GENERAL_CASH_BANK: GENERAL_CASH_BANK,
	GENERAL_CASH_BANK_LIST: GENERAL_CASH_BANK_LIST,
	GENERAL_COSTS: GENERAL_COSTS,
	GENERAL_INCOME_INVOICE: GENERAL_INCOME_INVOICE,
	GENERAL_INCOME_INVOICE_LIST: GENERAL_INCOME_INVOICE_LIST,
	GENERAL_JOURNAL: GENERAL_JOURNAL,
	GENERAL_LEDGER: GENERAL_LEDGER,
	GENERAL_LEDGER_REPORT: GENERAL_LEDGER_REPORT,
	GENERAL_SUPPLIER_INVOICE: GENERAL_SUPPLIER_INVOICE,
	GENERAL_SUPPLIER_INVOICE_LIST: GENERAL_SUPPLIER_INVOICE_LIST,
	GOODS_ISSUE: GOODS_ISSUE,
	GOODS_ISSUE_LIST: GOODS_ISSUE_LIST,
	GOODS_ISSUE_RETURN: GOODS_ISSUE_RETURN,
	GOODS_ISSUE_RETURN_LIST: GOODS_ISSUE_RETURN_LIST,
	GOODS_RECEIVE: GOODS_RECEIVE,
	GOODS_RECEIVE_LIST: GOODS_RECEIVE_LIST,
	GOODS_RETURN: GOODS_RETURN,
	GOODS_RETURN_LIST: GOODS_RETURN_LIST,
	GOODS_STOCK: GOODS_STOCK,
	GROUP_ACCESS: GROUP_ACCESS,
	HOLIDAY: HOLIDAY,
	HOME: HOME,
	HOSPITAL: HOSPITAL,
	IDENTITY_TYPE: IDENTITY_TYPE,
	INCOME_CASH_BANK: INCOME_CASH_BANK,
	INCOME_CASH_BANK_LIST: INCOME_CASH_BANK_LIST,
	INVENTORY_REPORT: INVENTORY_REPORT,
	INVALID_CREDENTIAL: INVALID_CREDENTIAL,
	INVALID_DATA_RETRIEVED: INVALID_DATA_RETRIEVED,
	INVALID_EMAIL: INVALID_EMAIL,
	INVALID_PASSWORD: INVALID_PASSWORD,
	INVALID_USER: INVALID_USER,
	JOBS: JOBS,
	LANGUAGE: LANGUAGE,
	LANGUAGE_VALUE: LANGUAGE_VALUE,
	LOADING: LOADING,
	LOGIN: LOGIN,
	LOGIN_TO_ACCOUNT: LOGIN_TO_ACCOUNT,
	LOGGING_IN: LOGGING_IN,
	LOGOUT: LOGOUT,
	MARITAL_STATUS: MARITAL_STATUS,
	MEAL_ABSENCE: MEAL_ABSENCE,
	MENU_ACCESS: MENU_ACCESS,
	METODE_PEMBAYARAN: METODE_PEMBAYARAN,
	MODULE: MODULE,
	NAME: NAME,
	NEWS: NEWS,
	NO_ACCOUNT: NO_ACCOUNT,
	OBJECT_MENU: OBJECT_MENU,
	OCCUPATION: OCCUPATION,
	ONLEAVE_TRANSACTION: ONLEAVE_TRANSACTION,
	ONLEAVE_TYPE: ONLEAVE_TYPE,
	ORDERS: ORDERS,
	ORGANIZATION: ORGANIZATION,
	ORGANIZATION_LEVEL: ORGANIZATION_LEVEL,
	ORGANIZATION_MANAGEMENT_LIST: ORGANIZATION_MANAGEMENT_LIST,
	ORGANIZATION_STRUCTURE: ORGANIZATION_STRUCTURE,
	OWNERSHIP: OWNERSHIP,
	PARAMETER: PARAMETER,
	PASSWORD: PASSWORD,
	PASSWORD_MIN_6: PASSWORD_MIN_6,
	PAYROLL_PERIODE: PAYROLL_PERIODE,
	PAYROLL_PROCESS: PAYROLL_PROCESS,
	PAYROLL_REPORT: PAYROLL_REPORT,
	PERMIT_EXIT_TRANSACTION: PERMIT_EXIT_TRANSACTION,
	PERMIT_EXIT_TYPE: PERMIT_EXIT_TYPE,
	PERMIT_IN_TRANSACTION: PERMIT_IN_TRANSACTION,
	PERMIT_IN_TYPE: PERMIT_IN_TYPE,
	PERSONALIZATION: PERSONALIZATION,
	PERSONNEL: PERSONNEL,
	PERSONNEL_REPORT: PERSONNEL_REPORT,
	POS: POS,
	POSITION: POSITION,
	PRICE_CATEGORY: PRICE_CATEGORY,
	PRODUCTION: PRODUCTION,
	PRODUCTION_OUTPUT: PRODUCTION_OUTPUT,
	PRODUCTION_OUTPUT_LIST: PRODUCTION_OUTPUT_LIST,
	PRODUCTION_PLANNING: PRODUCTION_PLANNING,
	PRODUCTION_PLANNING_MASTER: PRODUCTION_PLANNING_MASTER,
	PRODUCTION_PLANNING_REPORT: PRODUCTION_PLANNING_REPORT,
	PRODUCTION_PROCESS: PRODUCTION_PROCESS,
	PRODUCTION_REPORT: PRODUCTION_REPORT,
	PROFIT_LOSS: PROFIT_LOSS,
	PROVINCE: PROVINCE,
	PURCHASE_EXPEDITION: PURCHASE_EXPEDITION,
	PURCHASE_EXPEDITION_LIST: PURCHASE_EXPEDITION_LIST,
	PURCHASE_ORDER: PURCHASE_ORDER,
	PURCHASE_ORDER_LIST: PURCHASE_ORDER_LIST,
	PURCHASE_REQUEST: PURCHASE_REQUEST,
	PURCHASE_REQUEST_LIST: PURCHASE_REQUEST_LIST,
	PURCHASING: PURCHASING,
	PURCHASING_INFO_RECORD: PURCHASING_INFO_RECORD,
	QC: QC,
	QUALIFICATION_PARAMETER: QUALIFICATION_PARAMETER,
	QUALIFICATION_TEST: QUALIFICATION_TEST,
	RATE: RATE,
	READ_MORE: READ_MORE,
	RECRUIT_REQUEST_LIST: RECRUIT_REQUEST_LIST,
	RECURRING_TYPE: RECURRING_TYPE,
	REF_Q: REF_Q,
	RELIGION: RELIGION,
	REMINDER: REMINDER,
	REQUESTED_BY: REQUESTED_BY,
	RECRUIT_REQ_TRANSACTION: RECRUIT_REQ_TRANSACTION,
	RFQ: RFQ,
	ROMAWI: ROMAWI,
	SALES: SALES,
	SALES_AREA: SALES_AREA,
	SALES_EXPEDITION: SALES_EXPEDITION,
	SALES_EXPEDITION_LIST: SALES_EXPEDITION_LIST,
	SALES_FORECAST: SALES_FORECAST,
	SALES_FORECAST_LIST: SALES_FORECAST_LIST,
	SALES_LIST: SALES_LIST,
	SALES_ORDER: SALES_ORDER,
	SALES_ORDER_LIST: SALES_ORDER_LIST,
	SERVER_INFORMATION: SERVER_INFORMATION,
	SERVICE: SERVICE,
	SERVICE_LIST: SERVICE_LIST,
	SEX: SEX,
	SICKNESS_TRANSACTION: SICKNESS_TRANSACTION,
	SIGN_IN: SIGN_IN,
	SIGN_UP: SIGN_UP,
	SLIDE_SHOW: SLIDE_SHOW,
	SPECIFIC_NUMBER_RANGE_OBJECT: SPECIFIC_NUMBER_RANGE_OBJECT,
	STATUS: STATUS,
	STOCK_ADJUSMENT: STOCK_ADJUSMENT,
	STOCK_ADJUSTMENT_REPORT: STOCK_ADJUSTMENT_REPORT,
	SUPPLIER: SUPPLIER,
	SUPPLIER_INVOICE: SUPPLIER_INVOICE,
	SUPPLIER_INVOICE_LIST: SUPPLIER_INVOICE_LIST,
	TAX: TAX,
	TAX_ACCOUNTING: TAX_ACCOUNTING,
	TAX_WAGE_PROGRESSIF: TAX_WAGE_PROGRESSIF,
	TERMINATE_REQUEST: TERMINATE_REQUEST,
	TERMINATE_REQUEST_LIST: TERMINATE_REQUEST_LIST,
	THEME: THEME,
	TIME_MANAGEMENT_REPORT: TIME_MANAGEMENT_REPORT,
	TITLE: TITLE,
	TRANSFER_STOCK_IN: TRANSFER_STOCK_IN,
	TRANSFER_STOCK_LIST: TRANSFER_STOCK_LIST,
	TRANSFER_STOCK_OUT: TRANSFER_STOCK_OUT,
	TRANSACTION_LOG: TRANSACTION_LOG,
	TYPE_OF_SERVICE: TYPE_OF_SERVICE,
	UNIT_OF_MEASURE: UNIT_OF_MEASURE,
	USER: USER,
	USER_ACCESS: USER_ACCESS,
	USERS: USERS,
	VENDOR_DOCUMENT: VENDOR_DOCUMENT,
	VENDOR_PO: VENDOR_PO,
	WAGE_AND_TAX: WAGE_AND_TAX,
	WAGE_TYPE: WAGE_TYPE,
	WAREHOUSE: WAREHOUSE,
	WARNING_LETTERS: WARNING_LETTERS,
	WARNING_LETTERS_TYPE: WARNING_LETTERS_TYPE,
	WELCOME: WELCOME,
	WELCOME_BACK: WELCOME_BACK,
	WIDGET: WIDGET,
	WORK_TIME: WORK_TIME,
	WORKFLOW: WORKFLOW,
	YOU_ARE_NOT_AUTHORIZED: YOU_ARE_NOT_AUTHORIZED,
	YOUR_PROFILE: YOUR_PROFILE,
	INVALID_ENTRY_EMPTY: INVALID_ENTRY_EMPTY,
	INVALID_ENTRY_MIN: INVALID_ENTRY_MIN,
	INVALID_ENTRY_MIN_CHAR: INVALID_ENTRY_MIN_CHAR,
	INVALID_ENTRY_MAX: INVALID_ENTRY_MAX,
	INVALID_ENTRY_MAX_CHAR: INVALID_ENTRY_MAX_CHAR,
	INVALID_ENTRY_NUMBER: INVALID_ENTRY_NUMBER,
	INVALID_ENTRY_EMAIL: INVALID_ENTRY_EMAIL,
	INVALID_ENTRY_FORMAT: INVALID_ENTRY_FORMAT,
	INVALID_ENTRY_MATCH: INVALID_ENTRY_MATCH
};

export { ABSENCE_RULE, ABSENCE_SCHEDULE, ABSENCE_STATUS, ABSENCE_TRANSACTION, ACCOUNT, ACCOUNTING, ACCOUNTING_REPORT, ACCOUNT_PAYABLE_REPORT, ACCOUNT_PERIOD, ACCOUNT_RECEIVABLE_REPORT, ACCOUNT_TYPE, ACTIVITY, ADDRESS_ACCOUNTING, ADDRESS_BOOK, ADDRESS_TYPE, ADMIN, ADMIN_PANEL, APPLICANT, APPLICATION, ARTICLE, ARTICLE_GROUP, ARTICLE_PURCHASING_REPORT, ARTICLE_STATUS, ARTICLE_TYPE, AVERAGE_PRICE, BACK, BACK_TO_HOME, BALANCE_SHEET, BANK, BILL_OF_MATERIAL, BLOG, BROWSER, BUDGET, BUSINESS_GROUP, CASH_BANK, CATEGORY, CITY, COLOUR, COMMON, COMPANY, COMPANY_TYPE, COMPONENT, COMPONENT_CATEGORY, CONTACT_TYPE, COST_OF_GOODS_SOLD, COST_OF_SALES, COUNTRY, CREDIT_NOTE, CREDIT_NOTE_LIST, CURRENCY, CUSTOMER, CUSTOMER_GROUP, CUSTOMER_INVOICE, CUSTOMER_INVOICE_LIST, DASHBOARD, DATABASE, DEBIT_NOTE, DEBIT_NOTE_LIST, DEPARTMENT, DEPARTMENT_ACCOUNTING, DIRECT_FACTORY_WAGE_STANDARDS, EDUCATION, EDUCATION_MAJOR, EMAIL, EMPLOYEE, EMPLOYEE_BENEFIT, EMPLOYEE_ONLEAVE, EMPLOYEE_SCHEDULE, EMPLOYEE_STATUS, EMPLOYEE_TAX, EMPLOYEE_TYPE, EMPLOYEE_WAGE, ENTER_USER, EXPENSE_CASH_BANK, EXPENSE_CASH_BANK_LIST, FACTORY_WAGE_STANDARDS, FAMILY_RELATION, FILE_MANAGER, FINISH_GOODS_TRANSFER, FINISH_GOODS_TRANSFER_LIST, FISCAL_PROFIT_LOSS, FIX_ASSET, FORM_REQUEST, FORM_REQUEST_LIST, FORM_REQUEST_PLAN, FORM_REQUEST_PLAN_LIST, GENERAL_CASH_BANK, GENERAL_CASH_BANK_LIST, GENERAL_COSTS, GENERAL_INCOME_INVOICE, GENERAL_INCOME_INVOICE_LIST, GENERAL_JOURNAL, GENERAL_LEDGER, GENERAL_LEDGER_REPORT, GENERAL_SUPPLIER_INVOICE, GENERAL_SUPPLIER_INVOICE_LIST, GOODS_ISSUE, GOODS_ISSUE_LIST, GOODS_ISSUE_RETURN, GOODS_ISSUE_RETURN_LIST, GOODS_RECEIVE, GOODS_RECEIVE_LIST, GOODS_RETURN, GOODS_RETURN_LIST, GOODS_STOCK, GROUP_ACCESS, HOLIDAY, HOME, HOSPITAL, IDENTITY_TYPE, INCOME_CASH_BANK, INCOME_CASH_BANK_LIST, INVALID_CREDENTIAL, INVALID_DATA_RETRIEVED, INVALID_EMAIL, INVALID_ENTRY_EMAIL, INVALID_ENTRY_EMPTY, INVALID_ENTRY_FORMAT, INVALID_ENTRY_MATCH, INVALID_ENTRY_MAX, INVALID_ENTRY_MAX_CHAR, INVALID_ENTRY_MIN, INVALID_ENTRY_MIN_CHAR, INVALID_ENTRY_NUMBER, INVALID_PASSWORD, INVALID_USER, INVENTORY_REPORT, JOBS, LANGUAGE, LANGUAGE_VALUE, LOADING, LOGGING_IN, LOGIN, LOGIN_TO_ACCOUNT, LOGOUT, MARITAL_STATUS, MEAL_ABSENCE, MENU_ACCESS, METODE_PEMBAYARAN, MODULE, NAME, NEWS, NO_ACCOUNT, OBJECT_MENU, OCCUPATION, ONLEAVE_TRANSACTION, ONLEAVE_TYPE, ORDERS, ORGANIZATION, ORGANIZATION_LEVEL, ORGANIZATION_MANAGEMENT_LIST, ORGANIZATION_STRUCTURE, OWNERSHIP, PARAMETER, PASSWORD, PASSWORD_MIN_6, PAYROLL_PERIODE, PAYROLL_PROCESS, PAYROLL_REPORT, PERMIT_EXIT_TRANSACTION, PERMIT_EXIT_TYPE, PERMIT_IN_TRANSACTION, PERMIT_IN_TYPE, PERSONALIZATION, PERSONNEL, PERSONNEL_REPORT, POS, POSITION, PRICE_CATEGORY, PRODUCTION, PRODUCTION_OUTPUT, PRODUCTION_OUTPUT_LIST, PRODUCTION_PLANNING, PRODUCTION_PLANNING_MASTER, PRODUCTION_PLANNING_REPORT, PRODUCTION_PROCESS, PRODUCTION_REPORT, PROFIT_LOSS, PROVINCE, PURCHASE_EXPEDITION, PURCHASE_EXPEDITION_LIST, PURCHASE_ORDER, PURCHASE_ORDER_LIST, PURCHASE_REQUEST, PURCHASE_REQUEST_LIST, PURCHASING, PURCHASING_INFO_RECORD, QC, QUALIFICATION_PARAMETER, QUALIFICATION_TEST, RATE, READ_MORE, RECRUIT_REQUEST_LIST, RECRUIT_REQ_TRANSACTION, RECURRING_TYPE, REF_Q, RELIGION, REMINDER, REQUESTED_BY, RFQ, ROMAWI, SALES, SALES_AREA, SALES_EXPEDITION, SALES_EXPEDITION_LIST, SALES_FORECAST, SALES_FORECAST_LIST, SALES_LIST, SALES_ORDER, SALES_ORDER_LIST, SERVER_INFORMATION, SERVICE, SERVICE_LIST, SEX, SICKNESS_TRANSACTION, SIGN_IN, SIGN_UP, SLIDE_SHOW, SPECIFIC_NUMBER_RANGE_OBJECT, STATUS, STOCK_ADJUSMENT, STOCK_ADJUSTMENT_REPORT, SUPPLIER, SUPPLIER_INVOICE, SUPPLIER_INVOICE_LIST, TAX, TAX_ACCOUNTING, TAX_WAGE_PROGRESSIF, TERMINATE_REQUEST, TERMINATE_REQUEST_LIST, THEME, TIME_MANAGEMENT_REPORT, TITLE, TRANSACTION_LOG, TRANSFER_STOCK_IN, TRANSFER_STOCK_LIST, TRANSFER_STOCK_OUT, TYPE_OF_SERVICE, UNIT_OF_MEASURE, USER, USERS, USER_ACCESS, VENDOR_DOCUMENT, VENDOR_PO, WAGE_AND_TAX, WAGE_TYPE, WAREHOUSE, WARNING_LETTERS, WARNING_LETTERS_TYPE, WELCOME, WELCOME_BACK, WIDGET, WORKFLOW, WORK_TIME, YOUR_PROFILE, YOU_ARE_NOT_AUTHORIZED, id as default };
//# sourceMappingURL=id.mjs.map
